services:
  postgres:
    container_name: ecommerce-db
    image: postgres:latest
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - ./.db:/data/postgres
    ports:
      - '5432:5432'
